language: python
# branches: master
cache: pip

python:
  - '3.7'

install:
  - pip install .[full]
  - pip install mike==1.1.2

# Making sure its not a shallow clone
git:
  depth: false

env:
  global:
  - GH_URL: github.ibm.com
  - GH_REPO: CCHBAM/lightsaber.git
  - STABLE_VERSION: 0.3.0
  - DEV_VERSION: 0.3.0rc

stages:
  - name: doc_master
    if: branch = master
  - name: doc_dev
    if: branch = dev

jobs:
  include:
    - stage: doc_master
      script:
        - git remote set-url origin https://${GITHUB_TOKEN}@${GH_URL}/${GH_REPO} > /dev/null 2>&1
        - mike deploy --update-aliases "${STABLE_VERSION}" stable
        - git checkout gh-pages
        - git clean -fdx
        - ls -ltr
        - git push origin gh-pages
      verbose: true
      skip_cleanup: true
      keep_history: true
    - stage: doc_dev
      script:
        - git remote set-url origin https://${GITHUB_TOKEN}@${GH_URL}/${GH_REPO} > /dev/null 2>&1
        - mike deploy --update-aliases "${DEV_VERSION}" dev
        - git checkout gh-pages
        - git clean -fdx
        - ls -ltr
        - git push origin gh-pages
      verbose: true
      skip_cleanup: true
      keep_history: true
