language: python
# branches: master

python:
  - '3.7'

install:
  - pip install .[full]
  - pip install mike

# script:
  # # - pytest --cov
# # after_success:
# #   - coverage run --source=httpsuite -m pytest tests/
# #   - coveralls
  # - mkdocs build --verbose --clean
# #
# # before-deploy:
# #  - mkdocs build --verbose --clean --strict

# deploy:
#   - provider: pages:git
#     verbose: true
#     token: $GITHUB_TOKEN
#     edge: true
#     local_dir: site
#     on:
#       branch: master
#     github_url: github.ibm.com
#     skip_cleanup: true
#     keep_history: true

stages:
  - name: doc_master
    if: branch = master
  - name: doc_dev
    if: branch = dev

jobs:
  include:
    - stage: doc_master
      script: mike deploy --update-aliases 0.1 stable
      deploy:
        - provider: pages:git
          verbose: true
          token: $GITHUB_TOKEN
          edge: true
          local_dir: site
          github_url: github.ibm.com
          skip_cleanup: true
          keep_history: true
    - stage: doc_dev
      script: mike deploy --update-aliases 0.2.rc dev
      deploy:
        - provider: pages:git
          verbose: true
          token: $GITHUB_TOKEN
          edge: true
          local_dir: site
          github_url: github.ibm.com
          skip_cleanup: true
          keep_history: true
