name: dpm360-dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - cudatoolkit=10.2.*
  - future=0.18.2
  - jinja2=3.1.2
  - joblib=1.1.0
  - matplotlib=3.5.1
  - mlflow=1.2.0
  - nb_conda=2.2.1
  - numpy=1.22.3
  - pandas=1.4.2
  - pip=22.1.2
  - psutil=5.9.0
  - python-dateutil=2.8.2
  - pytorch=1.10.0
  - pytorch-lightning=1.6.4
  - pyyaml=6.0
  - ruamel.yaml=0.16.12
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - tabulate=0.8.10
  - tensorboard=2.9.1
  - toolz=0.11.2
  - torchmetrics=0.9.2
  - tqdm=4.64.0
  - pip:
      - ray>=1.13
