name: dpm360
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - h5py=2.10.0
  - hdf5=1.10.6
  - ipdb=0.13.3
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipywidgets=7.6.1
  - jinja2=2.11.2
  - joblib=0.17.0
  - matplotlib=3.3.3
  - nb_conda=2.2.1
  - numpy=1.19.4
  - pandas=1.1.4
  - pip=20.2.4
  - python-dateutil=2.8.1
  - pytorch=1.4.0
  - pyyaml=5.3.1
  - ruamel.yaml=0.16.12
  - scikit-learn=0.23.*
  - scipy=1.5.3
  - seaborn=0.11.1
  - tensorboard=2.4.0
  - torchvision=0.5.0
  - tzlocal=2.1
  - pip:
    - future
    - mlflow>=1.2.0
    - psutil
    - pytorch-lightning==0.8.5
    - ray
    - tabulate
    - toolz
    - tqdm
    - rpy2==3.1.0
