apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: minio
 namespace: ohdsi
 annotations:
  kubernetes.io/ingress.class: "public-iks-k8s-nginx"
spec:
  rules:
    - host: <extertnal link>
      http:
        paths:
          - path: /minio
            pathType: Prefix
            backend:
              service:
                name: minio-mlflow-db-service
                port:
                  number: 9000
  tls:
  - hosts:
    - <extertnal link>
    secretName: <secret - implementation may depend on cloud provider>
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: mlflow
 namespace: ohdsi
spec:
  rules:
    - host: <extertnal link>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mlflow-service
                port:
                  number: 5000
  tls:
  - hosts:
    - <extertnal link>
    secretName: <secret - implementation may depend on cloud provider>