apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dpm360-cronjob
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dpm360-cronjob
            image: ibmcom/dpm360-cronjob
            imagePullPolicy: Always
            env:
              - name: MLFLOW_API
                value: <YOUR_VALUE_HERE>
              - name: K8s_CLUSTER
                value: <YOUR_VALUE_HERE>
              - name: K8S_API_KEY
                value: <YOUR_VALUE_HERE>
              - name: K8S_API
                value: <YOUR_VALUE_HERE>
              - name: K8S_NAME_SPACE
                value: <YOUR_VALUE_HERE>
              - name: DPM360_SERVICE_BUILDER_HOST_NAME
                value: <YOUR_VALUE_HERE>
              - name: MLFLOW_TRACKING_URI
                value: <YOUR_VALUE_HERE>
              - name: MLFLOW_S3_ENDPOINT_URL
                value: <YOUR_VALUE_HERE>
              - name: AWS_SECRET_ACCESS_KEY
                value: <YOUR_VALUE_HERE>
              - name: AWS_ACCESS_KEY_ID
                value: <YOUR_VALUE_HERE>
          restartPolicy: OnFailure
