apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <%=ENV["MODEL_NAME"]%>-<%=ENV["MODEL_VERSION"]%>-ingress
  namespace: <%=ENV["K8S_NAME_SPACE"]%>
spec:
  rules:
    - host: <%=ENV["DPM360_SERVICE_BUILDER_HOST_NAME"]%>
      http:
        paths:
          - path: /<%=ENV["MODEL_NAME"]%>-<%=ENV["MODEL_VERSION"]%>
            pathType: Prefix
            backend:
              service:
                name: <%=ENV["MODEL_NAME"]%>-<%=ENV["MODEL_VERSION"]%>-service
                port:
                  number: <%=ENV["PORT"]%>
