apiVersion: v1
kind: Service
metadata:
  name: <%=ENV["MODEL_NAME"]%>-<%=ENV["MODEL_VERSION"]%>-service
  namespace: <%=ENV["K8S_NAME_SPACE"]%>
  labels:
    run: <%=ENV["MODEL_NAME"]%>-<%=ENV["MODEL_VERSION"]%>
spec:
  type: NodePort
  selector:
    run: <%=ENV["MODEL_NAME"]%>-<%=ENV["MODEL_VERSION"]%>
  ports:
    - protocol: TCP
      port: <%=ENV["PORT"]%>
      targetPort: <%=ENV["PORT"]%>